version: "3.9"

services:
  api:
    build: .
    container_name: creditcard_api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./dvc.yaml:/app/dvc.yaml
      - ./dvc.lock:/app/dvc.lock
      - ./.dvc:/app/.dvc
      - ./data:/app/data  # opcional (sรณ use se estiver desenvolvendo)
    environment:
      PYTHONUNBUFFERED: 1
    command: ["poetry", "run", "api"]
